version: '3'
services:
  www:
    container_name: app
    build: .
    depends_on:
      - db
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    restart: always
  db:
    container_name: dbHost
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=todoapp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - 33099:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PWA_PORT=3306